'use client';

import { useState } from 'react';
import { FileText, Download, Sparkles, RefreshCw } from 'lucide-react';
import { generatePDF } from '@/utils/pdfExport';
import ReactMarkdown from 'react-markdown';

const ExecutiveReport = () => {
    const [report, setReport] = useState<any>(null);
    const [loading, setLoading] = useState(false);
    const [generatingPdf, setGeneratingPdf] = useState(false);

    const handleGenerate = async () => {
        setLoading(true);
        try {
            const res = await fetch('/api/ai/executive-summary', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ period: 'This Month' })
            });

            if (!res.ok) {
                const errText = await res.text();
                // Check if it's rate limit
                if (res.status === 429) {
                    alert("Rate limit exceeded. Please wait a moment.");
                } else {
                    console.error("Report API Error:", errText);
                    alert("Failed to generate report. Backend may be offline or misconfigured.");
                }
                return;
            }

            const data = await res.json();
            setReport(data);
        } catch (e) {
            console.error(e);
        } finally {
            setLoading(false);
        }
    };

    const handleDownload = async () => {
        setGeneratingPdf(true);
        await generatePDF('executive-report-content', `Executive_Summary_${new Date().toISOString().split('T')[0]}.pdf`);
        setGeneratingPdf(false);
    };

    return (
        <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 col-span-full">
            <div className="flex justify-between items-center mb-6">
                <div className="flex items-center gap-2">
                    <FileText className="text-slate-600" size={24} />
                    <h3 className="text-xl font-bold text-slate-900">Executive Report</h3>
                </div>
                <div className="flex gap-2">
                    {!report ? (
                        <button
                            onClick={handleGenerate}
                            disabled={loading}
                            className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-70"
                        >
                            {loading ? <RefreshCw className="animate-spin" size={18} /> : <Sparkles size={18} />}
                            {loading ? 'Generating...' : 'Generate New Report'}
                        </button>
                    ) : (
                        <button
                            onClick={handleDownload}
                            disabled={generatingPdf}
                            className="flex items-center gap-2 px-4 py-2 border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition-colors"
                        >
                            <Download size={18} />
                            {generatingPdf ? 'Saving...' : 'Download PDF'}
                        </button>
                    )}
                </div>
            </div>

            {report && (
                <div className="bg-slate-50 p-8 rounded-xl border border-slate-200">
                    <div id="executive-report-content" className="bg-white p-8 shadow-sm rounded-lg max-w-3xl mx-auto">
                        <div className="border-b border-slate-200 pb-4 mb-6 flex justify-between items-end">
                            <div>
                                <h1 className="text-2xl font-bold text-slate-900">Executive Summary</h1>
                                <p className="text-slate-500 text-sm mt-1">Generated by AI Intelligence Platform</p>
                            </div>
                            <div className="text-right">
                                <p className="text-sm font-semibold text-slate-900">{report.period}</p>
                                <p className="text-xs text-slate-500">{report.report_date}</p>
                            </div>
                        </div>

                        <div className="prose prose-slate max-w-none">
                            <ReactMarkdown>{report.summary_markdown}</ReactMarkdown>
                        </div>

                        <div className="mt-8 pt-6 border-t border-slate-100 flex justify-between items-center">
                            <p className="text-xs text-slate-400">Confidential - Internal Use Only</p>
                            <div className="flex items-center gap-1 text-slate-400">
                                <Sparkles size={12} />
                                <span className="text-xs">Powered by Gemini</span>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ExecutiveReport;
